// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBQbeNJCj8nfCgIepzSj7bKmdlCBr1t7Q',
    appId: '1:280216792080:web:36bbb1b869d2da7c62ae95',
    messagingSenderId: '280216792080',
    projectId: 'dailytasksapp-e44b7',
    authDomain: 'dailytasksapp-e44b7.firebaseapp.com',
    storageBucket: 'dailytasksapp-e44b7.firebasestorage.app',
    measurementId: 'G-F5QPBV55VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2DbXcRQNr0pHp0x_ecxwzTHDIvCa29dI',
    appId: '1:280216792080:android:51e99133bed26ff962ae95',
    messagingSenderId: '280216792080',
    projectId: 'dailytasksapp-e44b7',
    storageBucket: 'dailytasksapp-e44b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABWrxZ57AUQF40wC--neOVzclIdMKTwiE',
    appId: '1:280216792080:ios:ed0db6de1c714e1062ae95',
    messagingSenderId: '280216792080',
    projectId: 'dailytasksapp-e44b7',
    storageBucket: 'dailytasksapp-e44b7.firebasestorage.app',
    iosBundleId: 'com.example.cis3334Project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABWrxZ57AUQF40wC--neOVzclIdMKTwiE',
    appId: '1:280216792080:ios:ed0db6de1c714e1062ae95',
    messagingSenderId: '280216792080',
    projectId: 'dailytasksapp-e44b7',
    storageBucket: 'dailytasksapp-e44b7.firebasestorage.app',
    iosBundleId: 'com.example.cis3334Project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBQbeNJCj8nfCgIepzSj7bKmdlCBr1t7Q',
    appId: '1:280216792080:web:e7f7ae646b73ac4462ae95',
    messagingSenderId: '280216792080',
    projectId: 'dailytasksapp-e44b7',
    authDomain: 'dailytasksapp-e44b7.firebaseapp.com',
    storageBucket: 'dailytasksapp-e44b7.firebasestorage.app',
    measurementId: 'G-8GX6EPEH5G',
  );
}
